### ISSUE TITLE
The setup.py installation file is missing.

### ISSUE THREAD

**Issue by Huangxiaodui** [jazzband/prettytable#230]
### What did you do?
I want to upgrade the prettytable in fedora. But when i use the newest version 3.6.0.tar.gz, the update the version in spec file, build the rpm failed. Because rpmbuild will use ```python3 setup.py build ```and ``` python3 setup.py install``` to install the package.
But there has not setup.py in 3.6.0.

I'd like to confirm why setup.py was deleted? Whether setup.py can be added again to simplify the spec content during RPM package compilation？

Thanks.

### What versions are you using?

* OS: Fefora 36
* Python: 
* PrettyTable: 3.6.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
# code goes here
```

**Comment by hugovk** [comment]
It was removed in https://github.com/jazzband/prettytable/pull/212 because we switched from setuptools to hatchling as the packaging build backend, making `setup.py` and `setup.cfg` redundant.

The metadata is now in `pyproject.toml`, following modern standards.

No, `setup.*` won't be added back, please build using `pyproject.toml` instead.

See https://discuss.python.org/t/tool-to-build-a-rpm-package-backed-by-pep-517/4020?u=hugovk for advice, and on a quick skim, it looks like https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/ has also been updated for `pyproject.toml `.

**Comment by ofek** [comment]
> it looks like https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/ has also been updated

Wow that's a really good document, thanks!

**Comment by Huangxiaodui** [comment]
@hugovk Thank you for your reply, have solved my question, this ISSUE will be closed.
